ALTER TABLE "chat_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "daily_closes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "earnings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "evidence_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "holding_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "holdings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "job_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "model_mappings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "model_proposals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "model_writes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "models" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "movement_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "movements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "provider_cache" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
