/** Pure helpers for turning a pull request body into something worth showing a model. */

const FOOTER_PATTERNS = [
  /^🤖\s*Generated with .*$/i,
  /^_?Generated by \[Claude Code\].*$/i,
  /^https?:\/\/claude\.ai\/code\/session_\S+$/i,
  /^Co-Authored-By:.*$/i,
];

/** Strips tool footers and session links; returns null when nothing meaningful is left. */
export function cleanBody(body: string | null | undefined): string | null {
  if (!body) return null;
  const lines = body
    .replace(/\r\n/g, "\n")
    .split("\n")
    .filter((line) => !FOOTER_PATTERNS.some((re) => re.test(line.trim())));
  const text = lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  return text ? text : null;
}

const MAX_SENTENCES = 3;

/** Keeps at most three sentences, dropping a trailing fragment left by a cut-off reply. */
export function trimSummary(text: string): string {
  const parts = text.replace(/\s+/g, " ").trim().split(/(?<=[.!?])\s+/);
  // A last part without closing punctuation is a cut-off fragment; drop it unless it is all we have.
  if (parts.length > 1 && !/[.!?]["')\]]?$/.test(parts[parts.length - 1])) parts.pop();
  return parts.slice(0, MAX_SENTENCES).join(" ");
}

function unescapeJson(s: string): string {
  try {
    return JSON.parse(`"${s}"`) as string;
  } catch {
    return s.replace(/\\"/g, '"');
  }
}

/**
 * Pulls headline and summary out of a model reply: proper JSON first, then a lenient scan of the
 * `"headline": "..."` / `"summary": "..."` pairs for replies cut off before the closing brace.
 */
export function parseSummaryReply(text: string): { headline: string; summary: string } | null {
  let headline = "";
  let summary = "";
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) {
    try {
      const parsed = JSON.parse(text.slice(start, end + 1)) as { headline?: unknown; summary?: unknown };
      headline = typeof parsed.headline === "string" ? parsed.headline.trim() : "";
      summary = typeof parsed.summary === "string" ? parsed.summary.trim() : "";
    } catch {
      /* fall through to the lenient scan */
    }
  }
  if (!headline && !summary) {
    const h = text.match(/"headline"\s*:\s*"((?:[^"\\]|\\.)*)"?/);
    const s = text.match(/"summary"\s*:\s*"((?:[^"\\]|\\.)*)"?/);
    headline = h ? unescapeJson(h[1]).trim() : "";
    summary = s ? unescapeJson(s[1]).trim() : "";
  }
  if (!headline && !summary) return null;
  summary = trimSummary(summary || headline);
  return { headline: headline || summary.split(/(?<=[.!?])\s/)[0].slice(0, 120), summary };
}

/** Calendar day in New York, so a late-evening merge is filed under the day the team saw it. */
export function mergeDayLabel(d: Date): string {
  return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "America/New_York" });
}
