import { describe, expect, it } from "vitest";
import { cleanBody, mergeDayLabel, parseSummaryReply, trimSummary } from "./clean";

describe("cleanBody", () => {
  it("strips tool footers and session links but keeps the summary", () => {
    const body = [
      "## Summary",
      "- Attribution tiles now use the S&P 500.",
      "",
      "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
      "",
      "https://claude.ai/code/session_01ABC",
      "",
      "_Generated by [Claude Code](https://claude.ai/code/session_01ABC)_",
      "Co-Authored-By: Claude <noreply@anthropic.com>",
    ].join("\n");
    expect(cleanBody(body)).toBe("## Summary\n- Attribution tiles now use the S&P 500.");
  });

  it("returns null for empty or footer-only bodies", () => {
    expect(cleanBody(null)).toBeNull();
    expect(cleanBody("")).toBeNull();
    expect(cleanBody("🤖 Generated with [Claude Code](https://claude.com/claude-code)\n")).toBeNull();
  });
});

describe("parseSummaryReply", () => {
  it("reads JSON wrapped in prose or fences", () => {
    expect(parseSummaryReply('Here you go:\n```json\n{"headline":"Charts got faster","summary":"Pages load quicker."}\n```')).toEqual({
      headline: "Charts got faster",
      summary: "Pages load quicker.",
    });
  });

  it("fills a missing headline from the summary", () => {
    expect(parseSummaryReply('{"summary":"Execs can now export holdings. It works on every page."}')).toEqual({
      headline: "Execs can now export holdings.",
      summary: "Execs can now export holdings. It works on every page.",
    });
  });

  it("recovers a reply cut off before the closing brace and keeps three sentences", () => {
    expect(parseSummaryReply('{"headline": "Admins pick the agent\\"s model", "summary": "One. Two. Three. Four is cut o')).toEqual({
      headline: 'Admins pick the agent"s model',
      summary: "One. Two. Three.",
    });
  });

  it("returns null when there is no usable JSON", () => {
    expect(parseSummaryReply("I cannot help with that.")).toBeNull();
    expect(parseSummaryReply("{}")).toBeNull();
    expect(parseSummaryReply("{not json}")).toBeNull();
  });
});

describe("trimSummary", () => {
  it("does not split on decimals or version numbers", () => {
    expect(trimSummary("Options include Ling 3.0 Flash Fin and Nemotron 3 Ultra. The choice applies to chat. Third one. Fourth.")).toBe(
      "Options include Ling 3.0 Flash Fin and Nemotron 3 Ultra. The choice applies to chat. Third one.",
    );
  });
});

describe("mergeDayLabel", () => {
  it("files a late-night UTC merge under the New York day", () => {
    expect(mergeDayLabel(new Date("2026-09-20T02:30:00Z"))).toBe("Sep 19, 2026");
  });
});
