import type { Tour } from "./types";

/**
 * Hoot's tour of everything added on Sep 25, 2026, for execs and admins (the only people who see every new page).
 * Copy rules: plain English, no Greek letters, every figure explained the first time, and every section says where
 * its numbers come from. Keep each line to a sentence or two; the page's own tooltips carry the detail.
 */
export const WHATS_NEW_TOUR_ID = "whats-new-2026-09-25";

// Said the same way everywhere, so the member learns each source once.
const PRICES = "Daily closing prices from Yahoo Finance, including dividends, saved every weekday evening after the market closes.";
const POSITIONS = "What the fund owns comes from the trade ledger, replayed to the latest close.";
const BENCHMARK = "The benchmark is the S&P 500's sector weights, which an exec saves on the ledger's Benchmark tab.";

const nav = (id: string) => `[data-tour="nav-${id}"]`;

export const WHATS_NEW_TOUR: Tour = {
  id: WHATS_NEW_TOUR_ID,
  chapters: [
    {
      id: "menu",
      label: "The menu",
      route: /^\//,
      steps: [
        {
          id: "menu",
          kind: "info",
          target: '[data-tour="sidebar"]',
          title: "The menu is organized now",
          body: "Pages are grouped by what they're for: Research (Holdings, me, the sell-side analyzer, models), Markets (movements, earnings, the economic calendar), Portfolio (attribution, and two new pages: Risk and Exposure), and Manage.",
        },
        {
          id: "scope",
          kind: "info",
          target: '[data-tour="scope"]',
          title: "Whose numbers you're looking at",
          what: "This card says whose holdings every page is showing. \"Whole fund\" is everyone.",
          how: "Click it to narrow the whole app to one sector team. If you switch while you're on Risk or Exposure, you stay on that page.",
        },
      ],
    },
    {
      id: "today",
      label: "Today",
      route: /^\/$/,
      steps: [
        {
          id: "go-today",
          kind: "go",
          target: nav("today"),
          title: "Today got a redesign",
          body: "The home page now reads top to bottom as one calm column: how the last session went, your teams, and what's coming up.",
          prompt: "Click Today in the menu.",
        },
        {
          id: "today-result",
          kind: "info",
          target: '[data-tour="today-result"]',
          title: "How the last session went",
          what: "The fund's return next to the S&P 500 and the difference, my written brief, the holdings that helped and hurt most, and how we did against the sector benchmark.",
          how: "Losses are in parentheses, like an accountant would write them. If a number changed after I wrote the brief, a note says so.",
          source: `${POSITIONS} ${PRICES} I write the brief at 5:05 pm ET from those numbers.`,
          ifMissing: "skip",
        },
        {
          id: "today-teams",
          kind: "info",
          target: '[data-tour="today-teams"]',
          title: "Teams",
          what: "Every team with its return and what it added to the fund. Open one to see each holding's price, today's move against the S&P 500, next earnings date and owner.",
          source: "Prices are live quotes from Yahoo Finance. Earnings dates come from Finnhub and Yahoo Finance.",
        },
        {
          id: "today-next",
          kind: "info",
          target: '[data-tour="today-next"]',
          title: "Coming up",
          what: "The next few earnings days for our holdings, and Sunday's weekly update, when the pack gets built and execs are asked for their notes.",
          source: "Earnings dates from Finnhub and Yahoo Finance.",
        },
      ],
    },
    {
      id: "risk",
      label: "Risk",
      route: /^(\/t\/[^/]+)?\/risk$/,
      steps: [
        {
          id: "go-risk",
          kind: "go",
          target: nav("risk"),
          title: "New page: Risk",
          body: "How bumpy the fund is, where that bumpiness comes from, and how today's holdings would have handled past crashes.",
          prompt: "Click Risk in the menu to open it.",
        },
        {
          id: "risk-lookback",
          kind: "info",
          target: '[data-tour="risk-toolbar"]',
          title: "How much history to use",
          what: "Every risk number on this page is measured over 6 months, 1 year (the default) or 2 years of daily price moves.",
          how: "A shorter window reacts faster to what markets are doing now. A longer one is steadier.",
          source: PRICES,
        },
        {
          id: "risk-headline",
          kind: "info",
          target: 'section[aria-label="Headline risk"]',
          title: "Four numbers for how bumpy the fund is",
          points: [
            { label: "Volatility", text: "how much the fund typically swings up or down in a year." },
            { label: "Beta", text: "how much it tends to move when the S&P 500 moves 1%." },
            { label: "Tracking error", text: "how far it tends to drift from its benchmark in a year." },
            { label: "1-day VaR", text: "a daily loss we'd expect to be beaten on only about 1 day in 20." },
          ],
          how: "We take what the fund owns today and replay a year of daily price moves on it. So it describes today's portfolio, not how the fund actually did.",
          source: `${POSITIONS} ${BENCHMARK}`,
        },
        {
          id: "risk-strip",
          kind: "info",
          target: '[data-tour="risk-strip"]',
          title: "More ways to read the same risk",
          points: [
            { label: "Expected shortfall", text: "the average loss on the worst 5% of days." },
            { label: "If the S&P 500 fell 10%", text: "roughly what we'd lose, in dollars, based on beta." },
            { label: "Effective positions", text: "how many equal-sized holdings the fund behaves like. Fewer means more concentrated." },
          ],
          source: "The same prices and positions as the four numbers above.",
        },
        {
          id: "risk-sectors",
          kind: "info",
          target: '[data-tour="risk-sectors"]',
          title: "Sectors, and where the risk comes from",
          what: "Each sector's weight next to the benchmark's, and its share of the fund's total risk.",
          how: "A sector's share of risk counts both its size and how much it moves with everything else we own. The shares add up to 100%.",
          source: `${PRICES} ${BENCHMARK}`,
        },
        {
          id: "risk-holdings",
          kind: "info",
          target: '[data-tour="risk-holdings"]',
          title: "Holdings by share of risk",
          what: "Each holding's size next to its share of the risk. A small position can carry a lot of risk if it's jumpy.",
          how: "The \"What if\" link on each row opens Backtesting with that holding trimmed by 2 percentage points, so you can see how the risk would change before you trade.",
          source: `${POSITIONS} ${PRICES}`,
        },
        {
          id: "risk-active",
          kind: "info",
          target: "#active-risk",
          title: "Why we drift from the benchmark",
          what: "Which holdings, and which parts of the benchmark we don't own, make the fund's returns differ from the benchmark's.",
          how: "It treats our holdings as bought and the benchmark's sector funds as sold, then splits the tracking error between them. \"+1 pp from cash\" shows what one more percentage point of a holding would do to it.",
          source: `${PRICES} ${BENCHMARK}`,
        },
        {
          id: "risk-realized",
          kind: "info",
          target: 'section[aria-label="Correlation and realized risk"]',
          title: "What moves together, and what actually happened",
          what: "Left: how closely our 15 largest holdings move together. The stronger the color, the more they move in step; red means they tend to move opposite ways. Right: the fund's real results, from its own daily value.",
          how: "The real-results side needs 20 trading days of the fund's own history. The ledger started Sep 17, so it fills in around mid-October.",
          source: `${PRICES} Real results come from the ledger's daily value of the fund.`,
        },
        {
          id: "risk-stress",
          kind: "info",
          target: 'section[aria-label="Historical stress tests"]:not([aria-busy])',
          title: "Stress tests: past crashes, today's holdings",
          what: "How today's holdings would have done in four rough patches: the COVID crash (2020), the 2022 rate shock, the SVB bank run (2023) and the August 2024 carry-trade unwind.",
          how: "We \"buy\" today's holdings at the start of each episode and hold them to the end. A company that wasn't trading yet is stood in by its sector fund. It's a replay, not a forecast. Click a row for the day-by-day path.",
          source: "Stored Yahoo Finance closing prices going back to February 2020.",
          waitMs: 15_000,
          ifMissing: "skip",
        },
        {
          id: "risk-method",
          kind: "info",
          target: '[data-tour="risk-method"]',
          title: "Check the math yourself",
          what: "The full method in words, the exact inputs as downloadable files, and the Excel formulas to recompute the headline numbers.",
          how: "Turn on Transparency (click your name at the bottom left) and every number gets a \"Show working\" link with the calculation done on the page's own figures.",
        },
      ],
    },
    {
      id: "exposure",
      label: "Exposure",
      route: /^(\/t\/[^/]+)?\/exposure$/,
      steps: [
        {
          id: "go-exposure",
          kind: "go",
          target: nav("exposure"),
          title: "New page: Exposure",
          body: "Where our money sits compared with the index: by sector, by company, and inside the ETFs we own.",
          prompt: "Click Exposure in the menu to open it.",
        },
        {
          id: "exposure-headline",
          kind: "info",
          target: 'section[aria-label="Headline exposure"]',
          title: "Our biggest bets",
          points: [
            { label: "Largest active bet", text: "the company (or sector) where our weight differs most from the index's." },
            { label: "Active Share", text: "how different the fund is from the index overall. 0% is an index fund; 100% owns nothing the index owns." },
          ],
          how: "We compare our weights with SPY's, company by company, after opening up our ETFs to see what's inside them.",
          source: `${POSITIONS} SPY's full holdings list comes from State Street, the fund's issuer.`,
        },
        {
          id: "exposure-toolbar",
          kind: "info",
          target: '[data-tour="exposure-toolbar"]',
          title: "Two ways to count an ETF",
          what: "\"ETFs as held\" counts an ETF like KRE as one position in its sector. \"Through ETFs\" splits it into the companies it actually owns.",
          how: "The lookback window works the same way it does on Risk.",
        },
        {
          id: "exposure-sectors",
          kind: "info",
          target: "#sectors",
          title: "Sectors against the benchmark",
          what: "Each sector's weight next to the benchmark's, with the biggest overweight first.",
          how: "Overweights and underweights always cancel out, because every dollar over somewhere is a dollar under somewhere else.",
          source: BENCHMARK,
        },
        {
          id: "exposure-factors",
          kind: "info",
          target: "#factors",
          title: "Which big market forces we lean into",
          what: "How the fund has tended to move with seven forces: the stock market, small versus large companies, value versus growth, momentum, interest rates, the dollar and oil.",
          how: "For each holding we measure how its daily moves have lined up with each force over the lookback window. Grey numbers mean there's no clear link. It's past behavior, not a prediction.",
          source: "Yahoo Finance prices for ETFs that stand in for each force: SPY, IWM, IVE and IVW, MTUM, TLT, UUP and USO.",
          ifMissing: "skip",
        },
        {
          id: "exposure-lookthrough",
          kind: "info",
          target: "#lookthrough",
          title: "Inside our ETFs",
          what: "Each ETF split into the companies it holds, added to anything we also own directly. If we own NVDA and an ETF that holds NVDA, you see the total.",
          how: "Our dollars in each ETF times each company's share of that ETF. The coverage table shows how complete and how recent each ETF's list is.",
          source: "Holdings files downloaded weekly from each ETF's issuer (State Street, iShares, First Trust, Roundhill), with Yahoo's top 10 as a fallback.",
          ifMissing: "skip",
        },
        {
          id: "exposure-stocks",
          kind: "info",
          target: "#stock-active",
          title: "Company-level over- and underweights",
          what: "The companies we hold more of than the index, and the big index names we hold less of or none of.",
          source: "SPY's full holdings list from State Street, compared with our holdings after looking through our ETFs.",
          ifMissing: "skip",
        },
      ],
    },
    {
      id: "backtesting",
      label: "Backtesting",
      route: /^\/backtesting$/,
      steps: [
        {
          id: "go-backtesting",
          kind: "go",
          target: nav("backtesting"),
          title: "Backtesting can ask \"what if?\"",
          body: "Try a change to the portfolio and see what it would do to risk before anyone trades.",
          prompt: "Click Backtesting in the menu.",
        },
        {
          id: "backtesting-quick",
          kind: "info",
          target: '[data-tour="bt-quick-trade"]',
          title: "Quick trade",
          what: "Trim or add to one holding by a few percentage points, in one line.",
          how: "Pick where the money comes from or goes to: cash, the other holdings in proportion, or one holding you name. Weights always add up to exactly 100%, and nothing changes in the real portfolio.",
          source: "It starts from the saved holding weights, not the trade ledger.",
        },
        {
          id: "backtesting-run",
          kind: "wait",
          target: '[data-tour="bt-run"]',
          until: '[data-tour="bt-risk-impact"]',
          title: "Give it a try",
          body: "Change a weight if you like, then run it. A new risk panel appears under the settings.",
          prompt: "Press Run backtest.",
        },
        {
          id: "backtesting-impact",
          kind: "info",
          target: '[data-tour="bt-risk-impact"]',
          title: "Risk impact",
          what: "The Risk page's numbers for the current weights and your changed weights, side by side, with the difference.",
          how: "It uses the same model as the Risk page with a 1-year window, whatever dates you picked for the replay.",
          source: `${PRICES} A company we don't track is fetched from Yahoo just for that run.`,
          waitMs: 20_000,
          ifMissing: "skip",
        },
        {
          id: "backtesting-save",
          kind: "info",
          target: '[data-tour="bt-save"]',
          title: "Save and share",
          what: "Name the scenario, add a note, and copy a link. Execs and admins share the fund's scenarios; each team shares its own.",
          source: "Saved in the app, never in the real portfolio.",
          ifMissing: "skip",
        },
      ],
    },
    {
      id: "calendar",
      label: "Economic calendar",
      route: /^\/t\/[^/]+\/economic-calendar$/,
      steps: [
        {
          id: "go-calendar",
          kind: "go",
          target: nav("economic-calendar"),
          title: "New on the Economic calendar",
          body: "Which upcoming releases matter most for our portfolio, and why.",
          prompt: "Click Economic calendar in the menu.",
        },
        {
          id: "calendar-lines",
          kind: "info",
          target: 'section[aria-label="Factor-sensitive releases"]',
          title: "Releases that move our kind of risk",
          what: "One line for each big release coming up, like CPI or the jobs report, with the forces it tends to move (rates, the dollar or oil) and how our fund has tended to react to those forces.",
          how: "Each release is matched to the forces it moves, then we read the fund's sensitivity from the Exposure page. Click a line to open that release.",
          source: "The release schedule from TradingView. Sensitivities from Exposure's factor numbers over 1 year.",
          waitMs: 8_000,
          ifMissing: "center",
          missing: "There are no big rates, dollar or oil releases coming up right now, so the \"Factor-sensitive releases\" box is hidden. When there are, it sits above the calendar with one line per release and how the fund tends to react.",
        },
      ],
    },
    {
      id: "hoot",
      label: "Hoot",
      route: /^\/t\/[^/]+\/agent$/,
      steps: [
        {
          id: "go-hoot",
          kind: "go",
          target: nav("hoot"),
          title: "I learned some new tricks",
          body: "I can look things up in a lot more places now.",
          prompt: "Click Hoot in the menu.",
        },
        {
          id: "hoot-tools",
          kind: "info",
          target: '[data-tour="ask-hoot"]',
          title: "New places I can look",
          points: [
            { label: "Economic data", text: "Treasury yields, inflation, unemployment and more from the St. Louis Fed's FRED database." },
            { label: "Betting markets", text: "odds from Kalshi and Polymarket, like the chance of a Fed cut." },
            { label: "Company background", text: "founders, headquarters and leadership from Wikipedia." },
            { label: "Calculations", text: "I can run Python on our own price and holdings data." },
            { label: "Tricky web pages", text: "pages that used to block me, and PDFs, now load." },
          ],
          how: "Just ask normally. I pick the source and cite it, so you can check every fact. Try one of these:",
          examples: [
            "What are the odds of a Fed rate cut at the next meeting?",
            "How has the 10-year Treasury yield moved this month?",
            "Compute the 60-day correlation between our two largest holdings.",
          ],
        },
      ],
    },
    {
      id: "wrap",
      label: "Wrap-up",
      route: /^\//,
      steps: [
        {
          id: "account",
          kind: "info",
          target: '[data-tour="account"]',
          title: "Your preferences live here",
          body: "Click your name any time for Theme (light or dark), Floating Hoot, Transparency (the math behind every number), and \"Replay what's new\" to watch this tour again.",
        },
      ],
    },
  ],
};
