import type { DerivedYear } from "./line-items";

/** A fiscal year with every line missing, for tests to fill in. */
export function blankYear(end: string, over: Partial<DerivedYear> = {}): DerivedYear {
  return {
    end,
    bsEnd: end,
    revenue: null,
    grossProfit: null,
    ebit: null,
    pretaxIncome: null,
    netIncome: null,
    eps: null,
    incomeTax: null,
    operatingCashFlow: null,
    capex: null,
    depreciation: null,
    interestExpense: null,
    sga: null,
    researchAndDevelopment: null,
    capitalizedSoftware: null,
    stockComp: null,
    buybacks: null,
    totalAssets: null,
    totalLiabilities: null,
    currentAssets: null,
    currentLiabilities: null,
    cash: null,
    debt: null,
    longTermDebt: null,
    equity: null,
    retainedEarnings: null,
    receivables: null,
    inventory: null,
    goodwill: null,
    ppe: null,
    leases: null,
    debtDueYear1: null,
    debtDueYear2: null,
    shares: null,
    sharesSource: null,
    dilutedShares: null,
    splitFactor: 1,
    accessions: [],
    ...over,
  };
}

/** A healthy company year: revenue 1,000, EBIT 200, pretax 190, tax 38 (20%), equity 800, debt 300, cash 100. */
export function healthyYear(end: string, over: Partial<DerivedYear> = {}): DerivedYear {
  return blankYear(end, {
    revenue: 1000,
    grossProfit: 400,
    ebit: 200,
    pretaxIncome: 190,
    incomeTax: 38,
    netIncome: 152,
    eps: 1.52,
    operatingCashFlow: 220,
    capex: 60,
    depreciation: 50,
    interestExpense: 10,
    sga: 150,
    stockComp: 10,
    buybacks: 40,
    totalAssets: 2000,
    totalLiabilities: 1200,
    currentAssets: 600,
    currentLiabilities: 400,
    cash: 100,
    debt: 300,
    longTermDebt: 250,
    equity: 800,
    retainedEarnings: 500,
    receivables: 150,
    inventory: 100,
    goodwill: 200,
    ppe: 700,
    shares: 100,
    sharesSource: "dei",
    ...over,
  });
}
